# Generated by Django 4.2.3 on 2023-07-12 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='введите название команды', max_length=50, verbose_name='Название команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='username',
            field=models.ForeignKey(help_text='укажите исключенных пользователей', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Удаленные пользователи'),
        ),
    ]
