version: '3.9'
services:
  web:
    container_name: django  
    build: .
    ports:
      - 8000:8000    
    command: python manage.py runserver 127.0.0.1:8000  
    volumes:
      - .:/my_site2
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"

volumes:
  postgres_data: